runtime: python
pythonVersion: 3.10
buildCommand: |
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  source $HOME/.cargo/env
  pip install --upgrade pip
  pip install -r requirements.txt
startCommand: python src/api.py
services:
  - type: web
    name: ai-cybersecurity-satellite
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT src.api:app
